# Generated by Django 5.2.11 on 2026-04-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_name', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_snapshots', to='orchestration.managedserver')),
            ],
            options={
                'ordering': ('resource_type', 'resource_name'),
            },
        ),
        migrations.CreateModel(
            name='ShareTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('read_groups', models.JSONField(blank=True, default=list)),
                ('change_groups', models.JSONField(blank=True, default=list)),
                ('full_groups', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_templates', to='orchestration.managedserver')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('server', 'name')},
            },
        ),
    ]
